bool check_all();
bool cont_init();
bool cont_fault(bool fault);
bool feeder_init();
bool carr_init();
bool carr_move();
bool carr_fault(bool fault);
bool bed_init();
void bed_down();
bool bed_fault(bool fault);
void feeder_up();
void feeder_down();
bool feeder_move();
bool feeder_fault(bool fault);
bool start(bool start);
void led_g_on();
void led_g_off();
void led_r_on();
void led_r_off();
void leds_buzz_update();
bool cont_full();
bool cont_insert();
void initSteppers();
bool pause_mode(bool pause);